### ISSUE TITLE
按步骤运行项目出现一个错误

### ISSUE THREAD

**Issue by SanlinBlackball** [jaggerwang/zqc-app-demo#1]
Unable to resolve module react/lib/ReactUpdates from /Users/a123/Downloads/zqc-app-demo-master/node_modules/react-native/Libraries/react-native/react-native.js: Module does not exist in the module map or in these directories:
  /Users/a123/Downloads/zqc-app-demo-master/node_modules/react-native/node_modules/react/lib
,  /Users/a123/Downloads/zqc-app-demo-master/node_modules/react/lib

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cache`.

RCTFatal + 104
-[RCTBatchedBridge stopLoadingWithError:] + 1138
__25-[RCTBatchedBridge start]_block_invoke_2 + 65
_dispatch_call_block_and_release + 12
_dispatch_client_callout + 8
_dispatch_main_queue_callback_4CF + 714
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
__CFRunLoopRun + 2073
CFRunLoopRunSpecific + 488
GSEventRunModal + 161
UIApplicationMain + 171
main + 111
start + 1

**Comment by jaggerwang** [comment]
Please confirm your react-native module is installed at subdirectory node_modules of your local project.
