### ISSUE TITLE
服务器是不是关掉了啊

### ISSUE THREAD

**Issue by JonsonHI** [jaggerwang/zqc-app-demo#11]
嘿嘿先给看看里面视频地方是怎么做的.

**Comment by jaggerwang** [comment]
没有阿，可以正常访问。Sorry，出于商业原因不能给出全部源代码。但如果对某个具体技术问题有疑问的，我可以回答。

视频上传这里其实并不复杂，使用 `react-native-image-crop-picker` 这个组件来选择图片或者视频，这个组件直接支持视频压缩，然后把压缩后的视频文件上传到服务端即可。

**Comment by JonsonHI** [comment]
十分感谢啊,我就是需要这个地方的代码 我试试这个插件吧

**Comment by JonsonHI** [comment]
进入相册后您是怎么弄成中文的啊

**Comment by jaggerwang** [comment]
![image](https://user-images.githubusercontent.com/1255011/32031692-6bb7876c-b9c8-11e7-98fd-0e77dacae50f.png)
没做特殊处理，picker组件内部会自动判断当前系统语言环境。

**Comment by JonsonHI** [comment]
大神我还是有些问题想问,我看了源码,发现您对视频的处理 其实把视频的截图放在首页的list列表上
这样大幅的降低了内存 和提高了流畅性.
我也看了接口的一些数据,都是字符串.
所以想请教下.
视频截图这个是怎么处理的.
我项目目前碰到了这个问题.
我直接用VIDEO 组件拿到视频在首页播放.页面卡的不行.
还请指导

**Comment by JonsonHI** [comment]
还有就是相册中文的问题,我是这么解决的
XCode里修改了PList文件里的Localization native development region为China
其实是系统的问题,并不是这个组件的问题

**Comment by jaggerwang** [comment]
@JonsonHI 视频上传到服务端后需要做处理，比如按不同码率进行压缩、提取封面图片等。预览的时候就可以使用封面图片，而不是加载原始视频。在球场的视频存储和处理用的是阿里云视频点播服务，当然你也可以选择其它服务商的。

**Comment by JonsonHI** [comment]
还是很感谢您的指导.这一块我跟后台对接下看看.
看到你的项目后,我就看了下相关的视频转码,网易和阿里都有这个
但是阿里貌似是收费的.不知道贵司是否有缴费

**Comment by jaggerwang** [comment]
肯定要收费，但是按量收费，用多少付多少。如果流量不大，费用很少。
