### ISSUE TITLE
赞叹：老师， 代码写的真是太好了！！！

### ISSUE THREAD

**Issue by lzldemo** [jaggerwang/zqc-app-demo#12]
越看越觉得代码组织的好， 模块封装的好， 状态管理的好！

**Comment by jaggerwang** [comment]
很高兴能够帮到你:)。这个版本的代码写完已经大半年了，后面抽时间做下重构，升级一下相关组件版本、优化一下代码结构。
如果对前端也感兴趣，推荐学习一下[zqc-web-demo](https://github.com/jaggerwang/zqc-web-demo)，相关课程目前还在制作中。

**Comment by lzldemo** [comment]
之前在上家公司借用你这个app的结构（ 5月之前）， 改写了一个app， 已经上线， 现在回过头看， 很多东西都没有吃透， 所以现在打算从头搭建， 重新写一个新应用， 边借鉴， 边消化。
在 2017年10月30日，上午10:35，Jagger Wang <notifications@github.com<mailto:notifications@github.com>> 写道：


很高兴能够帮到你:)。这个版本的代码写完已经大半年了，后面抽时间做下重构，升级一下相关组件版本、优化一下代码结构。
