### ISSUE TITLE
关于页面切换的问题

### ISSUE THREAD

**Issue by hlh6512500** [jaggerwang/zqc-app-demo#18]
为什么在（球场DEMO）在手机上运行起来，没有已经上线的软件（在球场）流畅，特别是页面切换的动画。感觉已经上线的软件页面切换特别自然、顺滑，是做了什么特别的处理吗？新人求教。

**Comment by jaggerwang** [comment]
线上版本是正式打包版本，打包过程中会去掉Debug相关的信息，同时会进行编译优化，所以性能会更好。

**Comment by hlh6512500** [comment]
请教下编译优化是指把代码压缩吗？

**Comment by jaggerwang** [comment]
不是，代码压缩只会提升下载性能，对于执行性能没有影响。编译优化是CPU指令级别的，这个在打正式发布包的时候由编译器来完成。

**Comment by hlh6512500** [comment]
能讲讲编译优化的具体步骤吗？谢谢啊，这几天老是觉得RN卡卡的，哎，找了好多方法。

**Comment by jaggerwang** [comment]
这个你得去请教写编译工具的人了，本人研究不多。

**Comment by hlh6512500** [comment]
`cd android && ./gradlew assembleRelease`
我是直接这样打包的，你们是怎么编译优化的呢，
你们打包时用的其他工具吗，或者你们打包方式与我的有什么不同。
求教啊，新人，被这个问题困扰很久了
