### ISSUE TITLE
打开应用报错

### ISSUE THREAD

**Issue by usergyt** [jaggerwang/zqc-app-demo#2]
你好，我打开应用报错，提示检查网络和位置出错，麻烦能告诉我怎么改下吗？

**Comment by jaggerwang** [comment]
请先确保手机网络通畅，并且授权了定位服务给应用。应用启动时会先检查网络和位置的状态，超时限制是5s。有的时候5s可能还没检查到，只需再重试即可。或者修改actions/bootstrap.js里的maxTimes值为更大。

**Comment by usergyt** [comment]
可以了谢谢！
