### ISSUE TITLE
 startTabBasedApp 加载所有tabs页面 会特别卡

### ISSUE THREAD

**Issue by usergyt** [jaggerwang/zqc-app-demo#3]
有个问题请教下，  Navigation.startTabBasedApp  会渲染所有的配置在tabs中的页面，我第二个是页面是打开相机，这样就会特别卡，怎么才能不渲染第二个页面，当我点击的时候才渲染这个页面？
![image](https://cloud.githubusercontent.com/assets/3840526/21322224/15ae5e9a-c653-11e6-917a-63e4d61e9e8c.png)

**Comment by jaggerwang** [comment]
https://github.com/wix/react-native-navigation/issues/74，react-native-navigation目前的作法就是一次渲染多个Tab页。
对于你提到的问题，暂时可以这样做。不要在第二个Tab页渲染时自动打开相机，而是让用户点击确认一下。

**Comment by usergyt** [comment]
thanks
