### ISSUE TITLE
项目运行错误

### ISSUE THREAD

**Issue by jiasaichao** [jaggerwang/zqc-app-demo#4]
按照步骤运行
iOS

> npm install
> react-native link
> react-native run-ios

出现：
** BUILD FAILED **

The following build commands failed:

        CompileC /Users/jiasaichao/Desktop/test/zqc-app-demo/ios/build/Build/Intermediates/ReactNativ
eNavigation.build/Debug-iphonesimulator/ReactNativeNavigation.build/Objects-normal/x86_64/RCCNavigati
onController.o RCCNavigationController.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0
.compiler
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/zaiqiuchang.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphone
simulator/zaiqiuchang.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

**Comment by jaggerwang** [comment]
Please follow the newest README doc. If there still have problems, give me feedback.

**Comment by jiasaichao** [comment]
@jaggerwang 就是按照你的说明clone下来后执行
> npm install
> react-native link
> react-native run-ios
你重新clone个试试行吗？

**Comment by jaggerwang** [comment]
The code is updated, please remove local copy and do as the new README doc.

**Comment by jiasaichao** [comment]
@jaggerwang
![simulator screen shot 2017 2 8 10 19 42](https://cloud.githubusercontent.com/assets/11605441/22741072/e8afb700-ee4c-11e6-8b23-b9f3c2de346a.png)
还是会出错，就是按照README执行的

**Comment by jaggerwang** [comment]
Show me the console log.

**Comment by jiasaichao** [comment]
@jaggerwang  我自己的问题，可以运行了。非常感谢

**Comment by 0xp3p3** [comment]
Hello @jiasaichao 
Does it work on right now? XCode 8.3? I have same error here now.
