### ISSUE TITLE
mac 运行出错

### ISSUE THREAD

**Issue by hechuanhua** [jaggerwang/zqc-app-demo#7]
2 warnings and 1 error generated.** BUILD FAILED **The following build commands failed:	CompileC /Users/hechuanhua/dev/zqc-app-demo/ios/build/Build/Intermediates/ReactNativeNavigation.build/Debug-iphonesimulator/ReactNativeNavigation.build/Objects-normal/x86_64/RCCNotification.o RCCNotification.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler(1 failure)Installing build/Build/Products/Debug-iphonesimulator/zaiqiuchang.appAn error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):Failed to install the requested applicationAn application bundle was not found at the provided path.Provide a valid path to the desired application bundle.Print: Entry, ":CFBundleIdentifier", Does Not ExistCommand failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/zaiqiuchang.app/Info.plistPrint: Entry, ":CFBundleIdentifier", Does Not Exist

**Comment by 0xp3p3** [comment]
same here.
my Xcode is 8.3

**Comment by onreadystatechange** [comment]
我的也出错了

**Comment by jaggerwang** [comment]
Reinstall react-native-navigation by `npm i react-native-navigation@2.0.0-experimental.266 -S`. For details to check the "Known issues" in README.

**Comment by jaggerwang** [comment]
请获取最新代码再次尝试。
